version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/sam/defer" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/sam/interact" # Location of package manifests
    schedule:
      interval: "daily"
