version: 2
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: [ "/sam/defer", "/sam/interact" ] # Location of package manifests
    schedule:
      interval: "weekly"
