AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  TempestBot

  Discord Interactions bot written in Kotlin and Python

Resources:
  TempestBotDeferFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sam/defer/defer
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64
      MemorySize: 512
      Timeout: 3
      Environment:
        Variables:
          INTERACT_FUNCTION: !Ref TempestBotInteractFunction
          PUBLIC_KEY:
            Ref: PublicKeyParameter
      Events:
        DiscordInteraction:
          Type: HttpApi
          Properties:
            Path: /
            Method: post
      Policies:
        - Statement:
            - Sid: Interact
              Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !GetAtt TempestBotInteractFunction.Arn
  TempestBotInteractFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sam/interact
      Handler: cloud.drakon.tempestbot.interact.Handler::handleRequest
      Runtime: java17
      Architectures:
        - arm64
      MemorySize: 2048
      Timeout: 900
      Environment:
        Variables:
          APPLICATION_ID:
            Ref: ApplicationIDParameter
          BOT_TOKEN:
            Ref: BotTokenParameter
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
          PUBLIC_KEY:
            Ref: PublicKeyParameter
          MONGODB_URL:
            Ref: MongoDbUrl
          MONGODB_DATABASE:
            Ref: MongoDbDatabase
          OPENAI_API_KEY:
            Ref: OpenAiApiKey
          CHAT_DEFAULT_ASSISTANT:
            Ref: ChatDefaultAssistant
      Policies:
        - Statement:
            - Sid: Translate
              Effect: Allow
              Action:
                - translate:TranslateText
                - comprehend:DetectDominantLanguage
              Resource: "*"

Outputs:
  TempestBot:
    Description: "API Gateway endpoint URL for TempestBot Defer function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"

  TempestBotDeferFunction:
    Description: "TempestBot Defer Lambda Function ARN"
    Value: !GetAtt TempestBotDeferFunction.Arn
  TempestBotDeferFunctionIamRole:
    Description: "Implicit IAM Role created for TempestBot Defer function"
    Value: !GetAtt TempestBotDeferFunctionRole.Arn

  TempestBotInteractFunction:
    Description: "TempestBot Interact Lambda Function ARN"
    Value: !GetAtt TempestBotInteractFunction.Arn
  TempestBotInteractFunctionIamRole:
    Description: "Implicit IAM Role created for TempestBot Interact function"
    Value: !GetAtt TempestBotInteractFunctionRole.Arn

Parameters:
  ApplicationIDParameter:
    Type: String
    NoEcho: True
  BotTokenParameter:
    Type: String
    NoEcho: True
  PublicKeyParameter:
    Type: String
    NoEcho: True
  MongoDbUrl:
    Type: String
    NoEcho: True
  MongoDbDatabase:
    Type: String
    NoEcho: True
    Default: tempestbot
  OpenAiApiKey:
    Type: String
    NoEcho: True
  ChatDefaultAssistant:
    Type: String
    Default: ""
