AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  TempestBot

  Discord Interactions bot written in Kotlin

Resources:
  TempestBotDeferFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sam/defer
      Handler: cloud.drakon.tempestbot.defer.Handler::handleRequest
      Runtime: java11
      Architectures:
        - arm64
      MemorySize: 1024
      Timeout: 3
      Environment:
        Variables:
          APPLICATION_ID:
            Ref: ApplicationIDParameter
          BOT_TOKEN:
            Ref: BotTokenParameter
          INTERACT_FUNCTION: !Ref TempestBotInteractFunction
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
          PUBLIC_KEY:
            Ref: PublicKeyParameter
      Events:
        DiscordInteraction:
          Type: Api
          Properties:
            Path: /
            Method: post
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref TempestBotInteractFunction
  TempestBotInteractFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sam/interact
      Handler: cloud.drakon.tempestbot.interact.Handler::handleRequest
      Runtime: java11
      Architectures:
        - arm64
      MemorySize: 512
      Timeout: 900
      Environment:
        Variables:
          APPLICATION_ID:
            Ref: ApplicationIDParameter
          BOT_TOKEN:
            Ref: BotTokenParameter
          PUBLIC_KEY:
            Ref: PublicKeyParameter

Outputs:
  TempestBot:
    Description: "API Gateway endpoint URL for TempestBot Defer function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  TempestBotDeferFunction:
    Description: "TempestBot Defer Lambda Function ARN"
    Value: !GetAtt TempestBotDeferFunction.Arn
  TempestBotDeferFunctionIamRole:
    Description: "Implicit IAM Role created for TempestBot Defer function"
    Value: !GetAtt TempestBotDeferFunctionRole.Arn

  TempestBotInteractFunction:
    Description: "TempestBot Interact Lambda Function ARN"
    Value: !GetAtt TempestBotInteractFunction.Arn
  TempestBotInteractFunctionIamRole:
    Description: "Implicit IAM Role created for TempestBot Interact function"
    Value: !GetAtt TempestBotInteractFunctionRole.Arn

Parameters:
  ApplicationIDParameter:
    Type: String
    NoEcho: True
  BotTokenParameter:
    Type: String
    NoEcho: True
  PublicKeyParameter:
    Type: String
    NoEcho: True
