AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  TempestBot

  Discord Interactions bot written in Kotlin

Resources:
  TempestBotDeferFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Defer
      Handler: cloud.drakon.tempestbot.defer.Handler::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 3
      Environment:
        Variables:
          APPLICATION_ID:
          BOT_TOKEN:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
          PUBLIC_KEY:
      Events:
        DiscordInteraction:
          Type: Api
          Properties:
            Path: /
            Method: post

Outputs:
  TempestBot:
    Description: "API Gateway endpoint URL for TempestBot Defer function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  TempestBotDeferFunction:
    Description: "TempestBot Defer Lambda Function ARN"
    Value: !GetAtt TempestBotDeferFunction.Arn
  TempestBotDeferFunctionIamRole:
    Description: "Implicit IAM Role created for TempestBot Defer function"
    Value: !GetAtt TempestBotDeferFunctionRole.Arn
