AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  TempestBot

  Discord Interactions bot written in Kotlin

Resources:
  TempestBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: cloud.drakon.tempestbot.Handler::handleRequest
      Runtime: java11
      Architectures:
        - arm64
      MemorySize: 4096
      Timeout: 900
      Environment:
        Variables:
          APPLICATION_ID:
            Ref: ApplicationIDParameter
          BOT_TOKEN:
            Ref: BotTokenParameter
          PUBLIC_KEY:
            Ref: PublicKeyParameter
          MONGODB_URL:
            Ref: MongoDbUrl
          MONGODB_DATABASE:
            Ref: MongoDbDatabase
      Events:
        DiscordInteraction:
          Type: Api
          Properties:
            Path: /
            Method: post
      Policies:
        - Statement:
            - Sid: Translate
              Effect: Allow
              Action:
                - translate:TranslateText
                - comprehend:DetectDominantLanguage
              Resource: "*"

Outputs:
  TempestBot:
    Description: "API Gateway endpoint URL for TempestBot function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  TempestBotFunction:
    Description: "TempestBot Lambda Function ARN"
    Value: !GetAtt TempestBotFunction.Arn
  TempestBotFunctionIamRole:
    Description: "Implicit IAM Role created for TempestBot function"
    Value: !GetAtt TempestBotFunctionRole.Arn

Parameters:
  ApplicationIDParameter:
    Type: String
    NoEcho: True
  BotTokenParameter:
    Type: String
    NoEcho: True
  PublicKeyParameter:
    Type: String
    NoEcho: True
  MongoDbUrl:
    Type: String
    NoEcho: True
  MongoDbDatabase:
    Type: String
    NoEcho: True
    Default: tempestbot
