name: Put application commands (Canary)
on:
  push:
    branches:
      - canary
    paths:
      - scripts/commands/commands.py
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - run: pip3 install requests boto3 --no-input
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - shell: bash
        env:
          APPLICATION_ID: ${{ secrets.CANARY_APPLICATION_ID }}
          BOT_TOKEN: ${{ secrets.CANARY_BOT_TOKEN }}
        run: |
          python3 scripts/commands/commands.py
