on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.7"
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - run: sam build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - shell: bash
        env:
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          PUBLIC_KEY_: ${{ secrets.PUBLIC_KEY }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --resolve-s3 --parameter-overrides "ApplicationIDParameter=$APPLICATION_ID BotTokenParameter=$BOT_TOKEN PublicKeyParameter=$PUBLIC_KEY MongoDbUrl=$MONGODB_URL"
